spring:
  jpa:
    show-sql: true # ???? ?? ?? ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true # SQL pretty print
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
#spring.jpa.properties.hibernate.dialect.storage_engine=innodb
#spring.datasource.hikari.jdbc-url=jdbc:h2:mem:testdb;MODE=MYSQL
#spring.datasource.hikari.username=sa

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG